title: Holi
hero_image: images/banner.png
description: Sprinkle some colour for Holi.
version: 1
listed: true
copyedit: false
last_tested: "2025-01-01"
landing: true
steps:
  - title: Holi
  - title: Add more circles
    completion:
      - engaged
  - title: Bigger circles
    completion:
      - internal
  - title: "🎉 You did it!"
    completion:
      - external
